name: ci
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup component add rustfmt
      - uses: ./.github/actions/cargo_cache
      - run: cargo fmt --all -- --check
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup component add clippy
      - uses: ./.github/actions/cargo_cache
      - run: cargo clippy --all-targets --all-features
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/cargo_cache
      - run: cargo test --all -- --nocapture
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    # env:
    #   CARGO_INCREMENTAL: 1
    steps:
      - uses: actions/checkout@v4
        # If you'd like to restore mtime, you have to disable shallow clone
        # with:
        #   fetch-depth: 0
      - uses: ./.github/actions/cargo_cache
      # If you'd like to enable incremental build,
      # you have to restore mtime for code.
      # @see https://github.com/MestreLion/git-tools/blob/main/git-restore-mtime
      # - name: Setup python
      #   uses: actions/setup-python@v2
      # - name: Restore mtime
      #   run: python ./path/to/git-restore-mtime.py
      - run: cargo build
