name: Deploy to AWS lambda
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    timeout_minutes: 10
    env:
    # CARGO_INCREMENTAL: 1
    steps:
      - uses: actions/checkout@v4
        # If you'd like to restore mtime, you have to disable shallow clone
        # with:
        #   fetch-depth: 0
      - uses: ./.github/actions/cargo_cache
      # If you'd like to enable incremental build,
      # you have to restore mtime for code.
      # @see https://github.com/MestreLion/git-tools/blob/main/git-restore-mtime
      # - name: Setup python
      #   uses: actions/setup-python@v2
      # - name: Restore mtime
      #   run: python ./path/to/git-restore-mtime.py
      - name: build
        run: cargo build
  # deploy:
  #   runs-on: ubuntu-latest
  #   timeout_minutes: 10
  #   needs:
  #     - build
  #   steps:
  #     - name: Configure AWS credentials
  #       uses: aws-actions/configure-aws-credentials@main
  #       with:
  #         aws-region: ${{ secrets.AWS_REGION }}
  #         role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
  #         role-session-name: NAME
  #     - name: Deploy
  #       run: echo "deploy"
